title: wakatakeru.work
description: >-
  æƒ…å ±ç³»ã®å¤§å­¦ç”Ÿã§ã™ã€‚ç ‚ä¸˜ã¨ã‚‰ãã ã®è¡—å‡ºèº«ã§ã€ã†ã©ã‚“å¤§å­¦ã«åœ¨ç±ã€‚
  ã€Œã•ã®å­—ã€ã£ã¦å‘¼ã°ã‚Œã¾ã™ï¼SDxã‚„ä»®æƒ³åŒ–æŠ€è¡“ãªã©ã«èˆˆå‘³ãŒã‚ã‚Šã¾ã™ã€‚
  å†™çœŸã¨ã£ãŸã‚Šã‚¢ãƒ‹ãƒ¡ã¿ãŸã‚ŠãŒè¶£å‘³ã€‚
  è»Šã®é‹è»¢ã‚‚å¥½ãğŸš— ãŠé…’ã¯å¿ƒã®æ—¥æ›œæ—¥ğŸ¶ ãƒ©ãƒ¼ãƒ¡ãƒ³ã‚‚å¥½ãğŸœ
url: "wakatakeru.work"
twitter_username: wakatakeru
github_username:  wakatakeru

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
