title: wakatakeru.work
description: >-
  ç ‚ä¸˜ç”Ÿã¾ã‚Œã§ã†ã©ã‚“ã®å›½ã«ä½ã‚€æƒ…å ±ç³»ã®å¤§å­¦ç”Ÿã®ãƒ–ãƒ­ã‚°ğŸš— ğŸ¶ğŸœğŸŸ
url: "wakatakeru.work"
twitter_username: wakatakeru
github_username:  wakatakeru

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
